using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Core.AudioDirector.UI;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class AudioDirectorWindow : DefaultWindow
{
    public AudioDirectorWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
