using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Content.Shared._Core.AudioDirector.Eui;
using Content.Client._Core.AudioDirector.UI.Controls;

namespace Content.Client._Core.AudioDirector.UI;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class AudioDirectorWindow : DefaultWindow
{
    public event Action? OnAddGroupPressed;
    public event Action<int>? OnDeleteGroupPressed;
    public event Action<int>? OnEditGroupPressed;
    private readonly Dictionary<int, bool> _groupExpandedStates = new();
    private readonly Dictionary<int, AudioGroupEuiData> _groupsById = new();
    private CreateAudioGroupWindow? _createGroupWindow;
    private bool _removeMode;


    public AudioDirectorWindow()
    {
        RobustXamlLoader.Load(this);

        AddGroupButton.OnPressed += _ =>
            OnAddGroupPressed?.Invoke();
        RemoveModeButton.OnPressed += _ =>
            ToggleRemoveMode();
    }

    public void SetGroups(AudioGroupEuiData[] groups)
    {
        _groupsById.Clear();

        foreach (var group in groups)
        {
            _groupsById[group.Id] = group;
        }

        GroupsContainer.RemoveAllChildren();

        if (groups.Length == 0)
        {
            GroupsContainer.AddChild(new Label
            {
                Text = "No audio groups created.",
                HorizontalAlignment = HAlignment.Center
            });

            RemoveModeButton.Disabled = true;
            return;
        }

        RemoveModeButton.Disabled = false;

        foreach (var group in groups)
        {
            var expanded = !_groupExpandedStates.TryGetValue(
                               group.Id,
                               out var savedExpanded)
                           || savedExpanded;

            var card = new AudioGroupCard(
                group,
                expanded);

            card.OnDeletePressed += groupId =>
                OnDeleteGroupPressed?.Invoke(groupId);
            card.SetRemoveMode(_removeMode);

            card.OnEditPressed += groupId =>
                OnEditGroupPressed?.Invoke(groupId);

            card.OnExpandedChanged +=
                OnGroupExpandedChanged;


            GroupsContainer.AddChild(card);
        }
    }

    private void ToggleRemoveMode()
    {
        _removeMode = !_removeMode;
        UpdateRemoveMode();
    }

    private void OnGroupExpandedChanged(
        int groupId,
        bool expanded)
    {
        _groupExpandedStates[groupId] = expanded;
    }

    private void UpdateRemoveMode()
    {
        foreach (var child in GroupsContainer.Children)
        {
            if (child is AudioGroupCard card)
                card.SetRemoveMode(_removeMode);
        }
    }
}
