using System.Linq;
using Content.Client.Administration.UI.CustomControls;
using Content.Client.Guidebook;
using Content.Client.Humanoid;
using Content.Client.Lobby;
using Content.Client.UserInterface.Controls;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ContentPack;
using Robust.Shared.Prototypes;
using Robust.Shared.Random;


namespace Content.Client._Other.ADT.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class SpeciesWindow : FancyWindow
{
    public event Action<ProtoId<SpeciesPrototype>>? ChooseAction;
    public ProtoId<SpeciesPrototype> CurrentSpecies;

    public HumanoidCharacterProfile Profile;

    private readonly IPrototypeManager _proto;
    private readonly IResourceManager _resMan;
    private readonly MarkingManager _markingManager;
    private readonly DocumentParsingManager _parsingMan;

    [Dependency] private readonly IRobustRandom _random = default!;


    public SpeciesWindow(
        HumanoidCharacterProfile profile,
        IPrototypeManager proto,
        IEntityManager entMan,
        LobbyUIController uIController,
        IResourceManager resManager,
        DocumentParsingManager parsing,
        MarkingManager markingManager)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Title = Loc.GetString("species-window-title");

        Profile = profile;
        _proto = proto;
        _resMan = resManager;
        _parsingMan = parsing;
        _markingManager = markingManager;

        Select.OnPressed += _ => ChooseAction?.Invoke(CurrentSpecies);

        var protoList = _proto.EnumeratePrototypes<SpeciesPrototype>()
            .Where(x => x.RoundStart)
            .ToList();

        protoList.Sort((x, y) => string.Compare(
            Loc.GetString(x.Name),
            Loc.GetString(y.Name),
            StringComparison.CurrentCultureIgnoreCase));

        AddSpeciesCategory("Классические", protoList, SpeciesCategory.Classic);
        AddSpeciesCategory("Нестандартные", protoList, SpeciesCategory.Unusual);
        AddSpeciesCategory("Особые", protoList, SpeciesCategory.Special);

        CurrentSpecies = Profile.Species;
        SelectSpecies(Profile.Species);
    }

    private void AddSpeciesCategory(string label, List<SpeciesPrototype> protoList, SpeciesCategory category)
    {
        var species = protoList.Where(x => x.Category == category).ToList();

        if (species.Count == 0)
            return;

        AddLabel(label);

        foreach (var item in species)
        {
            var button = new SpeciesButton(item)
            {
                HorizontalExpand = true,
                ToggleMode = true,
                Pressed = Profile.Species == item.ID,
                Text = Loc.GetString(item.Name),
                Margin = new Thickness(5f, 5f),
            };

            button.OnToggled += _ => SelectSpecies(item.ID);
            SpeciesContainer.AddChild(button);
        }
    }

    private void AddLabel(string text)
    {
        var container = new BoxContainer()
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(5f, 5f),
        };

        var label = new Label()
        {
            Text = text,
            StyleClasses = { "LowDivider" },
            Margin = new Thickness(2f, 2f),
        };

        var separator = new HSeparator()
        {
            Margin = new Thickness(2f, 2f, 2f, 4f),
        };

        container.AddChild(label);
        container.AddChild(separator);

        SpeciesContainer.AddChild(container);
    }

    private HumanoidCharacterProfile BuildPreviewProfile(ProtoId<SpeciesPrototype> speciesId) // Core patch
    {
        var speciesProto = _proto.Index(speciesId);
        var skinStrategy = _proto.Index(speciesProto.SkinColoration).Strategy;

        var skinColor = skinStrategy.ClosestSkinColor(Profile.Appearance.SkinColor);

        var sex = speciesProto.Sexes.Contains(Profile.Sex)
            ? Profile.Sex
            : speciesProto.Sexes[0];

        var appearance = HumanoidCharacterAppearance.EnsureValid(
            new HumanoidCharacterAppearance(
                Profile.Appearance.EyeColor,
                skinColor,
                new()),
            speciesId,
            sex,
            []);

        var previewProfile = HumanoidCharacterProfile.DefaultWithSpecies(speciesId, sex);

        previewProfile = previewProfile.WithName(Profile.Name);
        previewProfile = previewProfile.WithAge(Profile.Age);
        previewProfile = previewProfile.WithGender(Profile.Gender);
        previewProfile = previewProfile.WithSpawnPriorityPreference(Profile.SpawnPriority);
        previewProfile = previewProfile.WithPreferenceUnavailable(Profile.PreferenceUnavailable);
        previewProfile = previewProfile.WithJobPriorities(Profile.JobPriorities);
        previewProfile = previewProfile.WithAntagPreferences(Profile.AntagPreferences);

        foreach (var trait in Profile.TraitPreferences)
        {
            previewProfile = previewProfile.WithTraitPreference(trait, _proto);
        }

        foreach (var (_, loadout) in Profile.Loadouts)
        {
            previewProfile = previewProfile.WithLoadout(loadout);
        }

        previewProfile = previewProfile.WithCharacterAppearance(appearance);

        return previewProfile;
    }

    public void SelectSpecies(ProtoId<SpeciesPrototype> protoId)
    {
        DetailInfoContainer.DisposeAllChildren();

        foreach (var item in SpeciesContainer.Children)
        {
            if (item is not SpeciesButton button)
                continue;

            button.Pressed = protoId == button.Proto;
        }

        var proto = _proto.Index(protoId);
        CurrentSpecies = protoId;

        var previewProfile = BuildPreviewProfile(protoId); // Core patch

        JobPrototype? jobProto = null;

        var highJob = Profile.JobPriorities
            .FirstOrDefault(x => x.Value == JobPriority.High)
            .Key;

        if (!string.IsNullOrEmpty(highJob))
            _proto.TryIndex<JobPrototype>(highJob, out jobProto);


        Mob.LoadPreview(previewProfile, jobProto, false);
        JobLoadout.LoadPreview(previewProfile, jobProto, true);

        Select.Disabled = Profile.Species == protoId;

        var prosConsContainer = new BoxContainer()
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(5f, 5f),
            MaxWidth = 380f,
        };

        var prosConsLabel = new RichTextLabel()
        {
            Text = Loc.GetString("ui-species-pros-cons"),
            StyleClasses = { "LowDivider" },
            Margin = new Thickness(2f, 2f),
        };

        var separator = new HSeparator()
        {
            Margin = new Thickness(2f, 2f, 2f, 4f),
        };

        prosConsContainer.AddChild(prosConsLabel);
        prosConsContainer.AddChild(separator);
        DetailInfoContainer.AddChild(prosConsContainer);

        if (proto.Pros.Count <= 0 && proto.Special.Count <= 0 && proto.Cons.Count <= 0)
        {
            var noProsConsLabel = new RichTextLabel()
            {
                Text = Loc.GetString("ui-species-no-pros-cons"),
                Margin = new Thickness(4f),
            };

            DetailInfoContainer.AddChild(noProsConsLabel);
        }
        else
        {
            if (proto.Pros.Count > 0)
            {
                foreach (var item in proto.Pros)
                {
                    var label = new RichTextLabel()
                    {
                        Text = "[color=#13f244]- " + Loc.GetString(item) + "[/color]",
                        StyleClasses = { "LowDivider" },
                        Margin = new Thickness(4f, 2f),
                    };

                    prosConsContainer.AddChild(label);
                }

                prosConsContainer.AddChild(new Control() { MinHeight = 8f });
            }

            if (proto.Special.Count > 0)
            {
                foreach (var item in proto.Special)
                {
                    var label = new RichTextLabel()
                    {
                        Text = "- " + Loc.GetString(item),
                        StyleClasses = { "LowDivider" },
                        Margin = new Thickness(4f, 2f),
                    };

                    prosConsContainer.AddChild(label);
                }

                prosConsContainer.AddChild(new Control() { MinHeight = 8f });
            }

            if (proto.Cons.Count > 0)
            {
                foreach (var item in proto.Cons)
                {
                    var label = new RichTextLabel()
                    {
                        Text = "[color=#d63636]- " + Loc.GetString(item) + "[/color]",
                        StyleClasses = { "LowDivider" },
                        Margin = new Thickness(4f, 2f),
                    };

                    prosConsContainer.AddChild(label);
                }

                prosConsContainer.AddChild(new Control() { MinHeight = 8f });
            }
        }

        if (!proto.Description.HasValue)
            return;

        var descriptionPath = proto.Description.Value;

        try
        {
            using var file = _resMan.ContentFileReadText(descriptionPath);
            _parsingMan.TryAddMarkup(DetailInfoContainer, file.ReadToEnd());
        }
        catch (Exception e)
        {
            Logger.ErrorS("species-window", $"Failed to load species description '{descriptionPath}' for species '{protoId}': {e}");
        }
    }

    private sealed partial class SpeciesButton(ProtoId<SpeciesPrototype> proto) : Button
    {
        public ProtoId<SpeciesPrototype> Proto = proto;
    }
}
