using Content.Shared._Core.AudioDirector.Eui;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Core.AudioDirector.UI.Controls;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class AudioGroupCard : BoxContainer
{
    private bool _expanded;

    public int GroupId { get; }

    public event Action<int, bool>? OnExpandedChanged;
    public event Action<int>? OnDeletePressed;
    public event Action<int>? OnEditPressed;

    public AudioGroupCard(
        AudioGroupEuiData group,
        bool expanded)
    {
        RobustXamlLoader.Load(this);

        GroupId = group.Id;
        _expanded = expanded;

        GroupNameLabel.Text = group.Name;
        TargetTypeLabel.Text = group.TargetType.ToString();

        HeaderButton.OnPressed += _ =>
            ToggleExpanded();

        CollapseButton.OnPressed += _ =>
            ToggleExpanded();

        DeleteGroupButton.OnPressed += _ =>
            OnDeletePressed?.Invoke(GroupId);

        EditGroupButton.OnPressed += _ =>
            OnEditPressed?.Invoke(GroupId);

        UpdateExpandedState();
    }

    public void SetRemoveMode(bool enabled)
    {
        DeleteGroupButton.Visible = enabled;
    }

    private void ToggleExpanded()
    {
        _expanded = !_expanded;
        UpdateExpandedState();

        OnExpandedChanged?.Invoke(
            GroupId,
            _expanded);
    }

    private void UpdateExpandedState()
    {
        ContentContainer.Visible = _expanded;
        CollapseButton.Text = _expanded ? "▼" : "▶";
    }
}
